services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: agrogestor_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - agro_net

  backend:
    build:
      context: back-agrogestor
      dockerfile: Dockerfile
    volumes:
      - ./back-agrogestor:/var/www/html
    depends_on:
      - db
    # Necesitamos pasar estas variables a Laravel
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: '5432'
      DB_DATABASE: agrogestor_db
      DB_USERNAME: postgres
      DB_PASSWORD: 123456
      APP_ENV: local
      # Pon aquí tu key, asegurándote de escaparla
      APP_KEY: "base64:TU_APP_KEY"
    ports:
      - "8000:8000"
    entrypoint:
      - php
      - artisan
      - serve
      - --host=0.0.0.0
      - --port=8000
    networks:
      - agro_net

  frontend:
    build:
      context: front-agrogestor
      dockerfile: Dockerfile
    volumes:
      - ./front-agrogestor:/usr/src/app
    depends_on:
      - backend
    ports:
      - "4200:4200"
    networks:
      - agro_net

volumes:
  db_data:

networks:
  agro_net:
    driver: bridge
